services:
  redis:
    image: docker-registry-002.zeuslearning.com/zeuslearning/redis
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    command: >
      sh -c "redis-server --requirepass helloworld --user samriddh on >samriddh ~* +@all"
    volumes:
      - redis_data:/data

  mysql-db:
    image: docker-registry-002.zeuslearning.com/zeuslearning/mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: trainee_management_db
      MYSQL_USER: samriddh
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:
  redis_data:
    driver: local
