FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/sdk:10.0-alpine as build-env
ARG DOMAIN_OWNER
ARG NUGET_REPO_NAME
ARG CODEARTIFACT_AUTH_TOKEN
ARG REGION

WORKDIR /AppCode

RUN cat > nuget.config <<EOF
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="${NUGET_REPO_NAME}" value="https://zeuslearning-${DOMAIN_OWNER}.d.codeartifact.${REGION}.amazonaws.com/nuget/${NUGET_REPO_NAME}/v3/index.json" />
  </packageSources>
</configuration>
EOF

# EXPOSE 8080

# FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
# WORKDIR /src

COPY ./TraineeManagementApi/ ./TraineeManagementApi/
# COPY ./TraineeManagement.SharedData/ ./TraineeManagement.SharedData/

WORKDIR /AppCode/TraineeManagementApi

RUN dotnet nuget update source ${NUGET_REPO_NAME} -u "aws" -p "${CODEARTIFACT_AUTH_TOKEN}" --store-password-in-clear-text --configfile /AppCode/nuget.config


RUN dotnet restore --configfile /AppCode/nuget.config
RUN dotnet publish -c Release -o out --no-restore

FROM docker-registry-002.zeuslearning.com/zeuslearning/dotnet/aspnet:10.0-alpine as runtime
WORKDIR /App
COPY --from=build-env /AppCode/TraineeManagementApi/out .

# fallback setup
COPY ./TraineeManagementApi/appsettings.example.json ./
RUN cp appsettings.example.json appsettings.json


EXPOSE 8080
ENTRYPOINT ["dotnet", "TraineeManagementApi.dll"]