// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraineeManagementApi.db;

#nullable disable

namespace TraineeManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626132521_ProcessingJob")]
    partial class ProcessingJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TraineeManagementApi.Models.LearningTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpectedTechStack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("LearningTasks");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 56, 8, 624, DateTimeKind.Unspecified).AddTicks(3950),
                            Description = "Build a task tracker to creat",
                            DueDate = new DateTime(2026, 6, 20, 6, 54, 2, 743, DateTimeKind.Unspecified),
                            ExpectedTechStack = "manage tasks",
                            Status = "Published",
                            Title = "Task Tracker",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 56, 8, 624, DateTimeKind.Unspecified).AddTicks(3960)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 57, 37, 782, DateTimeKind.Unspecified).AddTicks(6670),
                            Description = "Build an API server with inMemory database",
                            DueDate = new DateTime(2026, 6, 23, 6, 54, 2, 743, DateTimeKind.Unspecified),
                            ExpectedTechStack = "ASP.NET Core WebAPI",
                            Status = "Published",
                            Title = "Trainee Management API - Phase 1",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 57, 37, 782, DateTimeKind.Unspecified).AddTicks(6680)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 57, 58, 632, DateTimeKind.Unspecified).AddTicks(1110),
                            Description = "Build an API server with sql database",
                            DueDate = new DateTime(2026, 6, 28, 6, 54, 2, 743, DateTimeKind.Unspecified),
                            ExpectedTechStack = "ASP.NET Core WebAPI",
                            Status = "Published",
                            Title = "Trainee Management API - Phase 2",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 57, 58, 632, DateTimeKind.Unspecified).AddTicks(1120)
                        });
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Mentor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Expertise")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Mentors");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 50, 9, 571, DateTimeKind.Unspecified).AddTicks(4110),
                            Email = "abhay.gori@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Abhay",
                            LastName = "Gori",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 50, 9, 571, DateTimeKind.Unspecified).AddTicks(4120)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 50, 31, 77, DateTimeKind.Unspecified).AddTicks(2600),
                            Email = "mentor2@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Rheetik",
                            LastName = "Sharma",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 50, 31, 77, DateTimeKind.Unspecified).AddTicks(2610)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 50, 50, 967, DateTimeKind.Unspecified).AddTicks(2200),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 50, 50, 967, DateTimeKind.Unspecified).AddTicks(2210)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 16, 940, DateTimeKind.Unspecified).AddTicks(2100),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 16, 940, DateTimeKind.Unspecified).AddTicks(2110)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 105, DateTimeKind.Unspecified).AddTicks(920),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 105, DateTimeKind.Unspecified).AddTicks(930)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 284, DateTimeKind.Unspecified).AddTicks(3300),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 284, DateTimeKind.Unspecified).AddTicks(3300)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 453, DateTimeKind.Unspecified).AddTicks(3010),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 453, DateTimeKind.Unspecified).AddTicks(3020)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 624, DateTimeKind.Unspecified).AddTicks(1720),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 624, DateTimeKind.Unspecified).AddTicks(1730)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 775, DateTimeKind.Unspecified).AddTicks(7100),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 775, DateTimeKind.Unspecified).AddTicks(7110)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 931, DateTimeKind.Unspecified).AddTicks(520),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 17, 931, DateTimeKind.Unspecified).AddTicks(520)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 18, 83, DateTimeKind.Unspecified).AddTicks(6480),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 18, 83, DateTimeKind.Unspecified).AddTicks(6490)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 51, 18, 297, DateTimeKind.Unspecified).AddTicks(7400),
                            Email = "mentor3@zeuslearning.com",
                            Expertise = "ASP .Net Core",
                            FirstName = "Jay Prakash",
                            LastName = "Yadav",
                            Status = "Active",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 51, 18, 297, DateTimeKind.Unspecified).AddTicks(7410)
                        });
                });

            modelBuilder.Entity("TraineeManagementApi.Models.ProcessingJob", b =>
                {
                    b.Property<string>("CorrelationId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("ErrorSummary")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Finished")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CorrelationId");

                    b.ToTable("ProcessingJobs");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("MentorId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReviewedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubmissionUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("TaskAssignmentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TaskAssignmentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.SubmissionFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GeneratedStorageName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.Property<string>("UploadedByUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("SubmissionFiles");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.TaskAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("LearningTaskId")
                        .HasColumnType("bigint");

                    b.Property<long>("MentorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("TraineeId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("LearningTaskId");

                    b.HasIndex("MentorId");

                    b.HasIndex("TraineeId");

                    b.ToTable("TaskAssignments");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Trainee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 48, 26, 726, DateTimeKind.Unspecified).AddTicks(420),
                            Email = "trainee1@example.com",
                            FirstName = "Samriddh",
                            LastName = "Singh",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 48, 26, 726, DateTimeKind.Unspecified).AddTicks(430)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 48, 42, 651, DateTimeKind.Unspecified).AddTicks(1340),
                            Email = "trainee2@example.com",
                            FirstName = "Ankit",
                            LastName = "Kumar",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 48, 42, 651, DateTimeKind.Unspecified).AddTicks(1350)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 48, 56, 664, DateTimeKind.Unspecified).AddTicks(5990),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 48, 56, 664, DateTimeKind.Unspecified).AddTicks(6000)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 0, 694, DateTimeKind.Unspecified).AddTicks(4270),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 0, 694, DateTimeKind.Unspecified).AddTicks(4280)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 0, 858, DateTimeKind.Unspecified).AddTicks(2750),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 0, 858, DateTimeKind.Unspecified).AddTicks(2760)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 14, DateTimeKind.Unspecified).AddTicks(6140),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 14, DateTimeKind.Unspecified).AddTicks(6150)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 146, DateTimeKind.Unspecified).AddTicks(7410),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 146, DateTimeKind.Unspecified).AddTicks(7420)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 320, DateTimeKind.Unspecified).AddTicks(8370),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 320, DateTimeKind.Unspecified).AddTicks(8380)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 484, DateTimeKind.Unspecified).AddTicks(3390),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 484, DateTimeKind.Unspecified).AddTicks(3390)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 654, DateTimeKind.Unspecified).AddTicks(5260),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 654, DateTimeKind.Unspecified).AddTicks(5270)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 815, DateTimeKind.Unspecified).AddTicks(7250),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 815, DateTimeKind.Unspecified).AddTicks(7260)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 974, DateTimeKind.Unspecified).AddTicks(660),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 1, 974, DateTimeKind.Unspecified).AddTicks(670)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 151, DateTimeKind.Unspecified).AddTicks(1600),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 151, DateTimeKind.Unspecified).AddTicks(1610)
                        },
                        new
                        {
                            Id = 14L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 295, DateTimeKind.Unspecified).AddTicks(3860),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 295, DateTimeKind.Unspecified).AddTicks(3870)
                        },
                        new
                        {
                            Id = 15L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 449, DateTimeKind.Unspecified).AddTicks(9120),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 449, DateTimeKind.Unspecified).AddTicks(9130)
                        },
                        new
                        {
                            Id = 16L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 608, DateTimeKind.Unspecified).AddTicks(7870),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 608, DateTimeKind.Unspecified).AddTicks(7880)
                        },
                        new
                        {
                            Id = 17L,
                            CreatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 830, DateTimeKind.Unspecified).AddTicks(6150),
                            Email = "trainee3@example.com",
                            FirstName = "Yash",
                            LastName = "Sharma",
                            Status = "Active",
                            TechStack = "ASP.Net core",
                            UpdatedDate = new DateTime(2026, 6, 17, 6, 49, 2, 830, DateTimeKind.Unspecified).AddTicks(6160)
                        });
                });

            modelBuilder.Entity("TraineeManagementApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDate = new DateTime(2026, 6, 26, 13, 25, 21, 111, DateTimeKind.Utc).AddTicks(1637),
                            Email = "samriddh.singh@zeuslearning.com",
                            PasswordHash = "AQAAAAIAAYagAAAAEP+QfNdJZtmZSCQUsvRTWt8NlKADYbY44q8GjYNIUhVn8c2ANxKiw50h4muvwf7ydg==",
                            Role = "Admin",
                            UpdatedDate = new DateTime(2026, 6, 26, 13, 25, 21, 111, DateTimeKind.Utc).AddTicks(1787),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Review", b =>
                {
                    b.HasOne("TraineeManagementApi.Models.Mentor", "Mentor")
                        .WithMany("Reviews")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraineeManagementApi.Models.Submission", "Submission")
                        .WithMany("Reviews")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Submission", b =>
                {
                    b.HasOne("TraineeManagementApi.Models.TaskAssignment", "TaskAssignment")
                        .WithMany("Submissions")
                        .HasForeignKey("TaskAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskAssignment");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.SubmissionFile", b =>
                {
                    b.HasOne("TraineeManagementApi.Models.Submission", "Submission")
                        .WithOne("SubmissionFile")
                        .HasForeignKey("TraineeManagementApi.Models.SubmissionFile", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.TaskAssignment", b =>
                {
                    b.HasOne("TraineeManagementApi.Models.LearningTask", "LearningTask")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("LearningTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraineeManagementApi.Models.Mentor", "Mentor")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TraineeManagementApi.Models.Trainee", "Trainee")
                        .WithMany("TaskAssignments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LearningTask");

                    b.Navigation("Mentor");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.LearningTask", b =>
                {
                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Mentor", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("TaskAssignments");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Submission", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("SubmissionFile");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.TaskAssignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("TraineeManagementApi.Models.Trainee", b =>
                {
                    b.Navigation("TaskAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
